### ISSUE TITLE
Roadmap to 4.0

### ISSUE THREAD

**Issue by klausi** [drupal-graphql/graphql#936]
Planning meta issue for open tasks before we can make a 4.0 release. This list might not be complete yet.

## Beta targets
Goal: do any big API breaking changes before the first beta release.
- [x] Add default value resolver: if incoming value is NULL use the default
- [ ] Performance test, compare scenarios with JSON API
- [ ] Resolve as many TODO comments in the code base as possible

## Whishlist
Can be implemented any time even after a stable release. Should not cause API breaks.
- [ ] Configuration UI with autocomplete for available data types, data producers, schema mapping options
- [ ] Workspaces support (global current workspace context, similar to language)
- [ ] Subtree caching of queries

**Comment by joaogarin** [comment]
Looks like https://github.com/drupal-graphql/graphql/pull/941 could be relevant for " Add default value resolver: if incoming value is NULL use the default"

**Comment by klausi** [comment]
Default value resolver was added in #941 by @pmelab

**Comment by klausi** [comment]
I think I will make one last alpha release today and then the next release can be beta1, I don't think we have big blockers left.

**Comment by klausi** [comment]
I released beta2 today, but I think any of the next releases could be a stable 1.0.

**Comment by klausi** [comment]
I released beta3 today because we have a bit of an API break in #1086 . Hopefully this is the last beta release and if we don't hear about bigger issues then I think we can release 4.0 soon!

**Comment by klausi** [comment]
4.0 has been released!
